#!/usr/bin/env python3
"""Generate docker-compose.prod.yml, .env, and optionally a Caddyfile for N users.

Usage:
    python deploy.py --users alice:pass1 bob:pass2 charlie:pass3 dave:pass4
    python deploy.py --users alice:pass1 bob:pass2 --domain aqm.example.com
    python deploy.py --users alice:pass1 bob:pass2 --up
"""

import argparse
import os
import subprocess
import sys


def parse_users(raw: list[str]) -> list[tuple[str, str]]:
    """Parse NAME:PASSWORD pairs, returning [(name, password), ...]."""
    users = []
    for entry in raw:
        if ":" not in entry:
            sys.exit(f"Error: '{entry}' must be NAME:PASSWORD")
        name, password = entry.split(":", 1)
        if not name or not password:
            sys.exit(f"Error: '{entry}' — name and password cannot be empty")
        if not name.isalnum():
            sys.exit(f"Error: username '{name}' must be alphanumeric")
        users.append((name, password))
    names = [u[0] for u in users]
    if len(names) != len(set(names)):
        sys.exit("Error: duplicate usernames")
    return users


def generate_env(users: list[tuple[str, str]]) -> str:
    """Generate .env file contents."""
    db_password = os.urandom(24).hex()
    lines = [
        "# ── AQM Production Environment (auto-generated by deploy.py) ──",
        "",
        "# PostgreSQL password",
        f"AQM_DB_PASSWORD={db_password}",
        "",
        "# Per-user login passwords",
    ]
    for name, password in users:
        lines.append(f"AQM_{name.upper()}_PASSWORD={password}")
    lines += ["", "# Flask session signing keys"]
    for name, _ in users:
        lines.append(f"FLASK_SECRET_{name.upper()}={os.urandom(24).hex()}")
    lines.append("")
    return "\n".join(lines)


def generate_compose(users: list[tuple[str, str]], base_port: int) -> str:
    """Generate docker-compose.prod.yml contents."""
    # Fixed services
    yml = """\
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: aqm
      POSTGRES_USER: aqm_user
      POSTGRES_PASSWORD: "${AQM_DB_PASSWORD:-aqm_prod_password}"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./AQM_Database/aqm_server/migrations:/docker-entrypoint-initdb.d

  coin-server:
    build: .
    restart: unless-stopped
    command: >
      uvicorn AQM_Database.aqm_server.api:app
      --host 0.0.0.0 --port 8000
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      PG_DSN: "postgresql://aqm_user:${AQM_DB_PASSWORD:-aqm_prod_password}@postgres:5432/aqm"
"""

    # User services
    for i, (name, _) in enumerate(users):
        port = base_port + i
        others = [(n, base_port + j) for j, (n, _) in enumerate(users) if n != name]
        contact_names = " ".join(o[0] for o in others)
        contact_ports = " ".join(str(o[1]) for o in others)
        upper = name.upper()

        yml += f"""
  {name}:
    build: .
    restart: unless-stopped
    ports:
      - "{port}:{port}"
    command: >
      python -m AQM_Database.flask_app.app
      --user {name} --port {port} --host 0.0.0.0
      --contacts {contact_names} --contact-ports {contact_ports}
    depends_on:
      - coin-server
    environment:
      REDIS_HOST: redis
      PG_DSN: "postgresql://aqm_user:${{AQM_DB_PASSWORD:-aqm_prod_password}}@postgres:5432/aqm"
      AQM_CONTACT_HOST_TEMPLATE: docker
      AQM_PASSWORD: "${{AQM_{upper}_PASSWORD:-aqm-demo-2026}}"
      FLASK_SECRET_KEY: "${{FLASK_SECRET_{upper}:-change-me-{name}}}"
"""

    yml += """
volumes:
  redis_data:
  pg_data:
"""
    return yml


def generate_caddyfile(users: list[tuple[str, str]], base_port: int, domain: str) -> str:
    """Generate Caddyfile with per-user subdomains."""
    blocks = []
    for i, (name, _) in enumerate(users):
        port = base_port + i
        blocks.append(f"{name}.{domain} {{\n    reverse_proxy {name}:{port}\n}}")
    return "\n\n".join(blocks) + "\n"


def generate_compose_with_caddy(compose: str, domain: str) -> str:
    """Add caddy service to compose YAML (inserted before volumes)."""
    caddy_service = f"""
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
"""
    # Insert before volumes: section and add caddy volumes
    compose = compose.replace(
        "\nvolumes:\n",
        caddy_service + "\nvolumes:\n",
    )
    compose = compose.rstrip()
    compose += "\n  caddy_data:\n  caddy_config:\n"
    return compose


def main():
    parser = argparse.ArgumentParser(description="Generate AQM deployment config for N users")
    parser.add_argument(
        "--users", nargs="+", required=True, metavar="NAME:PASS",
        help="User definitions as NAME:PASSWORD pairs (minimum 2)",
    )
    parser.add_argument("--domain", help="Domain for Caddyfile generation (e.g. aqm.example.com)")
    parser.add_argument("--base-port", type=int, default=5000, help="Starting port (default 5000)")
    parser.add_argument("--up", action="store_true", help="Run docker compose up after generating")
    args = parser.parse_args()

    users = parse_users(args.users)
    if len(users) < 2:
        sys.exit("Error: need at least 2 users")

    # Generate files
    env_content = generate_env(users)
    compose_content = generate_compose(users, args.base_port)

    if args.domain:
        caddyfile_content = generate_caddyfile(users, args.base_port, args.domain)
        compose_content = generate_compose_with_caddy(compose_content, args.domain)

    # Write files
    script_dir = os.path.dirname(os.path.abspath(__file__))

    env_path = os.path.join(script_dir, ".env")
    with open(env_path, "w") as f:
        f.write(env_content)
    print(f"Wrote {env_path}")

    compose_path = os.path.join(script_dir, "docker-compose.prod.yml")
    with open(compose_path, "w") as f:
        f.write(compose_content)
    print(f"Wrote {compose_path}")

    if args.domain:
        caddy_path = os.path.join(script_dir, "Caddyfile")
        with open(caddy_path, "w") as f:
            f.write(caddyfile_content)
        print(f"Wrote {caddy_path}")

    print(f"\nGenerated config for {len(users)} users:")
    for i, (name, _) in enumerate(users):
        print(f"  {name}: port {args.base_port + i}")

    if args.up:
        print("\nStarting services...")
        subprocess.run(
            ["docker", "compose", "-f", compose_path, "up", "-d", "--build"],
            cwd=script_dir,
            check=True,
        )


if __name__ == "__main__":
    main()
